name: Publish to NPM
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        NPM_PERSONAL_TOKEN: ${{ secrets.NPM_PERSONAL_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies and build 🔧
        run: npm install
      - name: Update Git Credentials
        run: |
          git config --global user.name 'mathumi'
          git config --global user.email 'mathumi@users.noreply.github.com'
      - name: Publish package on NPM 📦
        run: npm version patch && npm publish
      - name: Push changes
        run: |
          git commit -am "Publish"
          git push